### ISSUE TITLE
Exoplanets with MeerKAT

### ISSUE THREAD

**Issue by cyriltasse** [cyriltasse/DynSpecMS#23]
Build a merged exoplanetary systems catalog from

`https://exoplanet.eu/home/`

`https://exoplanetarchive.ipac.caltech.edu/`

And a Gaia dr3 comparison stars catalog:

`https://gea.esac.esa.int/archive/`

**Comment by cyriltasse** [comment]
Query gaia stuff

https://github.com/cyriltasse/AnalyseDynSpecMS/blob/ff622233396f8d45f6d5ab28b0754380d2c1dfe3/Catalogs/ClassGaiaQuery.py

**Comment by cyriltasse** [comment]
`ms2dynspec.py --ms <you.ms> --data DATA --model PREDICT_SUB --rad 1. --noff 30 --DoTar 0 --OutDirName Test --NCPU 90 --srclist test.txt`

with `test.txt` being the file containing the info for your targets: Src_Label(str), ra(deg), dec(deg), Src_Type(str)

**Comment by talonmyburgh** [comment]
Will look to see if I can patch this tomorrow if @cyriltasse doesn't get to it first. Doesn't look like it will be too complicated.

**Comment by talonmyburgh** [comment]
@bngcebetsha are you on branch: `MTilde_ASync_weights_mergeJones_merge`

**Comment by bngcebetsha** [comment]
@talonmyburgh no, I'm on `main`

**Comment by bngcebetsha** [comment]
The problem I am now getting is caused by my MS - something I will need to sort out:

```
(venv) bngcebetsha@stevie:/data4/sirothia/proxima_btry/msdir/DynSpecMS$ python3 ms2dynspec.py --ms ../1556208112_20190425-J1429_6240-corr.ms --data DATA --model PREDICT_SUB --rad 1. --noff 30 --NCPU 90 --srclist proxima_source.csv 
 - 16:55:50 - AsyncProcessPool             | Fixing parent process to vthread 0
 - 16:55:50 - AsyncProcessPool             | Worker affinities not specified, leaving unset
 - 16:55:50 - ClassMS                      | found 1 MSs matching ../1556208112_20190425-J1429_6240-corr.ms
 - 16:55:50 - ClassMS                      | ../1556208112_20190425-J1429_6240-corr.ms: selecting DDID 0
 - 16:55:50 - ClassMS                      | ../1556208112_20190425-J1429_6240-corr.ms: selecting field 0
 - 16:55:50 - ClassMS                      | ../1556208112_20190425-J1429_6240-corr.ms: non-default column DATA
 - 16:55:50 - ClassMS                      | 1 MS section(s) selected
 - 16:55:50 - DynSpecMS                    | DynSpecMS version v1.0-115-g0c47a03 starting up
  Reading metadata...............   1/1 [==================================================] 100%  - 0'00" 
Traceback (most recent call last):
  File "ms2dynspec.py", line 198, in <module>
    main(args)
  File "ms2dynspec.py", line 133, in main
    options=args)
  File "/data4/sirothia/proxima_btry/msdir/DynSpecMS/ClassDynSpecMS.py", line 132, in __init__
    self.ReadMSInfos()
  File "/data4/sirothia/proxima_btry/msdir/DynSpecMS/ClassDynSpecMS.py", line 776, in ReadMSInfos
    self.NTimesGrid=int(np.ceil((tmax-tmin)/dtBin))
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
```

**Comment by bngcebetsha** [comment]
permission to push changes to the branch @cyriltasse ? I updated a few imports

**Comment by cyriltasse** [comment]
Hi thanks, I had a similar problem lately but I fixed it, @bngcebetsha what branch are you using?

**Comment by bngcebetsha** [comment]
> Hi thanks, I had a similar problem lately but I fixed it, @bngcebetsha what branch are you using?

@cyriltasse  thanks for your response, I am running `MTilde_ASync_weights_mergeJones_merge` branch

**Comment by cyriltasse** [comment]
Can you try with `SplitCatalog` branch?

**Comment by bngcebetsha** [comment]
> `SplitCatalog`

I still get the time resolution issue I reported here - https://github.com/cyriltasse/DynSpecMS/issues/23#issuecomment-2061463083

thanks I think I should have a closer look at this myself.

**Comment by bngcebetsha** [comment]
@cyriltasse  - I was wondering when you will have time to chat about this method - https://github.com/cyriltasse/DynSpecMS/blob/fd32cac4d907383b8c9df4ff3e121fba64d604d1/ClassDynSpecMS.py#L989

Its raising an exception during processing.

**Comment by o-smirnov** [comment]
@bngcebetsha I can see this method appeared in later DDF branches. Try the ``UseAPP_kMS_MeerKLASS`` branch for instance.

**Comment by cyriltasse** [comment]
Yeah that could well be that you need a more recent version of DDFacet... @bngcebetsha maybe I can give you a singularity image that as all up to date branches?

**Comment by bngcebetsha** [comment]
@cyriltasse  that would be nice, thanks @o-smirnov . I forked and hacked away at `DynSpecMS` till it produced something. I still need to understand the output fits files I got. Thanks for all the help and the tool
